sudo: required
services:
  - docker

before_install:
  - docker build -t heeyoonkim0405/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true heeyoonkim0405/docker-react1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-847794985585"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"